### ISSUE TITLE
BQ connector shouldn't throw shaded internal exceptions.

### ISSUE THREAD

**Issue by functicons** [GoogleCloudPlatform/bigdata-interop#239]
This is from a StackOverflow [question](https://stackoverflow.com/questions/57414647/why-is-dataproc-using-this-weird-shaded-version-of-the-json-package-and-how-do-i). I think the problem is that, BQ connector shouldn't throw shaded internal exceptions, because it made users hard to catch the exception. Instead it should create its own exception class, e.g., BqConnectorException and set the shaded internal exceptions as cause.

**Comment by AndyClausen** [comment]
I'm the author of the SO question.

I thought it might be worth mentioning that I'm using the new GCS Connector along this one, and last I checked that one threw the correct exception.

**Comment by medb** [comment]
>I'm using the new GCS Connector along this one

What GCS connector do you mean when you say "new"?

**Comment by AndyClausen** [comment]
Actually, I just noticed it's called "client library". It's just confusing seeing how there's also a connector.

I'm using both the client library (`com.google.cloud:google-cloud-storage`) and the connector (`com.google.cloud.bigdataoss:gcs-connector`).

I've had compatibility issues between these two before because of different Guava versions IIRC.

**Comment by medb** [comment]
@AndyClausen what application are you writing? You shouldn't use GCS and BQ connectors if you are not writing Hadoop or Spark job.

And why did you try to use both `com.google.cloud:google-cloud-storage` and `com.google.cloud.bigdataoss:gcs-connector` in the same application?

**Comment by AndyClausen** [comment]
I'm writing a spark job in Scala. I couldn't find functionality to list objects in a bucket with the connector, and couldn't find functionality to read a single object with the client library.

**Comment by medb** [comment]
@AndyClausen You can use GCS connector to list objects and get a single object.

Because GCS connector implements Hadoop [FileSystem](https://hadoop.apache.org/docs/current/api/org/apache/hadoop/fs/FileSystem.html) interface, you need to look for Spark Scala HCFS/HDFS examples and replace `hdfs://` file system with `gs://` in the path:
https://www.programcreek.com/scala/org.apache.hadoop.fs.FileSystem

**Comment by AndyClausen** [comment]
Hmm, that's interesting. I remember I looked for it for hours, maybe days, some months ago, but never found. I'll probably look into it again, thanks.
