### ISSUE TITLE
Append/ Overwrite to table via Spark API

### ISSUE THREAD

**Issue by samelamin** [GoogleCloudPlatform/bigdata-interop#42]
Hi Guys

I have been using this project to set up a spark connector to BQ,  I noticed that writing to a bq table via `.saveAsNewAPIHadoopDataset(hadoopConf)` results in my table getting duplicate data. I understand that because I am calling the save method twice (2 different batch jobs)

The problem is the source data doesnt have the ability to be streamed so it leads me to rerunning the job in a batch manner, its an API

This means that some of the data returned per job is the same which results on duplicate data being inserted

Is there a way to set up the connector so that it recognises the records are the same and either append or overwrite them?

I think the job configuration allows me to to this via the create/write disposition

Is there something similar to that using the API?

**Comment by dennishuo** [comment]
Unfortunately, the notion of "duplicate records" isn't really a top-level supported concept in BigQuery because BigQuery isn't indexed as a transactional database. On the one hand, BigQuery doesn't know whether identical records were intentionally inserted multiple times or if they were intended to be unique, and for the connector, while writing to BigQuery, there's no efficient way to determine if a particular record is already in the table without performing a full scan to do the lookup.

This StackOverflow answer from a BigQuery engineer shows how you can use queries in BigQuery itself to remove duplicates in post-processing: http://stackoverflow.com/a/36686205/3777211
