### ISSUE TITLE
Supply GCS credentials through the command line

### ISSUE THREAD

**Issue by eyalba** [GoogleCloudPlatform/bigdata-interop#75]
Hi,

To my understanding in order to execute a distcp command to upload data from our local Hadoop cluster into GS I have to define the following parameter google.cloud.auth.service.account.json.keyfile and make sure all worker nodes in my cluster have the keyfile available locally.

Since I want to allow multiple users across the org to upload data to their own bucket in GS using their own credentials, I want to be able to send GS credentials through the distcp command line like we currently do when uploading data to S3.

Is there a solution in the pipeline which should enable this functionality?

Best,

Eyal

**Comment by cyxxy** [comment]
Now you can implement an [AccessTokenProvider](https://github.com/GoogleCloudPlatform/bigdata-interop/blob/master/util-hadoop/src/main/java/com/google/cloud/hadoop/util/AccessTokenProvider.java) interface. In your case, you can implement it to read from the command line.

**Comment by eyalba** [comment]
Hi @cyxxy, 
Can you elaborate more on how do I accomplish it when wanting to only execute Distcp command with variables?

**Comment by cyxxy** [comment]
Or something like
hadoop distcp -Dfs.gs.accesstoken=xxxx ...., which also requires implementation.

**Comment by cyxxy** [comment]
Actually you can specify user credentials in command line, but due to a bug it is not working for distcp at the moment. There is a similar issue https://github.com/GoogleCloudPlatform/bigdata-interop/issues/62, so I'm going to close this one and track the work in https://github.com/GoogleCloudPlatform/bigdata-interop/issues/62.

You can use client credentials in the following way:
`hadoop distcp -Dfs.gs.auth.client.id=<client-id> -Dfs.gs.auth.client.secret=<client-secrect> -Dfs.gs.auth.service.account.enable=false gs://... gs://...`

And you can get the client credentials from https://console.cloud.google.com/apis/credentials, click on "Create credentials", select "OAuth client ID" then "Other".

**Comment by steveloughran** [comment]
> similar to the s3a inline credential feature ("hdfs fs -ls s3a://key:secret@my-bucket/")

you don't want that. Leaks secrets through all the logs. This is why S3A tells you off for trying, and it is up for discussion as to whether to disable it. The core defensible distcp use case was when copying across accounts, but with per-bucket secrets, that can be done other ways.

**Comment by eyalba** [comment]
Thanks for the info guys. 
So how do you suggest enabling a cross org solution where each user can upload to its bucket (using distcp) without sharing the same key file for all users saved into the HDFS config file?

**Comment by medb** [comment]
Each user can specify their own key file in `--files` argument (i.e. `hadoop --files=<KEY_FILE> distcp ...`), Hadoop will take care of distributing it on cluster nodes, and theoretically it could work.

We didn't test this approach though, so it will be nice if you can give it a try and post results here.

**Comment by eyalba** [comment]
Where did you get --files config parameter from?
How will Hadoop know to distribute local user files to hdfs?

**Comment by medb** [comment]
This is [standard](http://hadoop.apache.org/docs/r2.9.0/hadoop-project-dist/hadoop-common/CommandsManual.html) `hadoop` command parameter. It should be `-files` though (was with excess dash before).
